export const languages = {
  en: { name: "English" },
  sr: { name: "Serbian" },
};

export const ENGLISH_TRANSLATION = {
  home: "Home",
  courses: "Courses",
  contact: "Contact",
  login: "Log in",
  register: "Register",
  hero: "Brush your path",
  all_courses: "All courses",
  featured_courses: "In the spotlight",
  featured_courses_description: "Explore what’s trending and take your picks",
  add_to_cart: "Add to cart",
  see_all_courses: "See all courses",
  about_me: "About Me",
  about:
    "I am Teodora Grubor. Nine years ago, when I first picked up a brush, I realized that makeup was not just a hobby – it was my life’s calling. My idea was to create a place where knowledge is accessible to everyone who wants to learn and contribute to the growth of the beauty community. So far, makeup artists from Serbia, Croatia, Bosnia and Herzegovina, Montenegro, North Macedonia, Slovenia, Switzerland, Germany, and even Thailand have completed training with me. Online courses allow an even wider audience to develop their creativity, improve their skills, and achieve their goals, whether they see makeup as a hobby or a career. If you haven’t learned from me yet, now is the perfect time for us to spark creativity and build confidence together. And if you already know my work, thank you for being here again! 💕",
  reviews_title: "Words that inspire me",
  reviews_subtitle:
    "Real stories from students who turned their passion into success.",
  courses_title: "Featured Courses",
  courses_subtitle: "Explore what’s trending and take your picks",
  course_overview: "Course Overview",
  cart: "Cart",
  total: "Total",
  checkout: "Check Out",
  my_courses: "My Courses",
  my_profile: "My Profile",
  change_password: "Change Password",
  old_password: "Old Password",
  new_password: "New Password",
  confirm_password: "Confirm Password",
  first_name: "First Name",
  last_name: "Last Name",
  email: "Email",
  update: "Update",
  logout: "Logout",
  dashboard: "Dashboard",
  where_to_find_me: "Where to find me?",
};

export const SERBIAN_TRANSLATION = {
  home: "Početna",
  courses: "Kursevi",
  contact: "Kontakt",
  login: "Prijavi se",
  register: "Registruj se",
  hero: "Brush your path",
  all_courses: "Svi kursevi",
  featured_courses: "Popularni kursevi",
  featured_courses_description:
    "Pronađi svoje favorite i tehniku koju želiš da usavršiš",
  add_to_cart: "Dodaj u korpu",
  see_all_courses: "Vidi sve kurseve",
  about_me: "O meni",
  about:
    "Ja sam Teodora Grubor. Pre 9 godina, kada sam prvi put uzela četkicu u ruke, shvatila sam da šminka nije samo hobi – to je moj životni poziv. Moja ideja bila je da stvorim mesto gde znanje postaje dostupno svima koji žele da uče i doprinesu rastu beauty zajednice. Do sada su edukacije kod mene završili šminkeri iz Srbije, Hrvatske, Bosne i Hercegovine, Crne Gore, Makedonije, Slovenije, Švajcarske, Nemačke, pa čak i sa Tajlanda. Online kursevi omogućavaju još širem krugu ljudi da razvijaju svoju kreativnost, usavrše veštine i ostvare ciljeve, bilo da šminkanje vide kao hobi ili karijeru. Ako još nisi učila/o od mene, sada je savršen trenutak da zajedno podstaknemo kreativnost i izgradimo samopouzdanje. A ako već poznaješ moj rad, hvala ti što si ponovo ovde! 💕",
  reviews_title: "Reči koje me pokreću",
  reviews_subtitle:
    "Real stories from students who turned their passion into success.",
  courses_title: "Svi kursevi",
  courses_subtitle: "Pronađi svoje favorite i tehniku koju želiš da usavršiš",
  course_overview: "Detalji kursa",
  cart: "Korpa",
  total: "Ukupno",
  checkout: "Nastavi sa kupovinom",
  my_courses: "Kursevi",
  my_profile: "Profil",
  change_password: "Promeni lozinku",
  old_password: "Stara lozinka",
  new_password: "Nova lozinka",
  confirm_password: "Potvrdi lozinka",
  first_name: "Ime",
  last_name: "Prezime",
  email: "Email",
  update: "Izmeni",
  logout: "Odjavi se",
  dashboard: "Admin Panel",
  where_to_find_me: "Gde me možete naći?",
};
